name: Deploy S3 Website

on:
  push:
    branches:
      - main # Trigger on pushes to main branch

jobs:
  terraform:
    name: Terraform Apply
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code
      - name: Checkout Repo
        uses: actions/checkout@v3

      # 2️⃣ Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.0

      # 3️⃣ Configure AWS credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AKIASNVQCIYVAD5F2R7X }}
          aws-secret-access-key: ${{ secrets.cE9lxOUpgoYa3kjOwSrrnRdrjbuCcOontm31vOmr }}
          aws-region: ${{ secrets.eu-west-1 }}

      # 4️⃣ Terraform init
      - name: Terraform Init
        run: terraform init

      # 5️⃣ Terraform plan
      - name: Terraform Plan
        run: terraform plan

      # 6️⃣ Terraform apply
      - name: Terraform Apply
        run: terraform apply -auto-approve
